version: "3.9"

services:
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    container_name: m_wallet_db
    image: postgres:15
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

volumes:
  pg_data: